### ISSUE TITLE
" Models aren't loaded yet"  error issued when I try to run migrate or syncdb

### ISSUE THREAD

**Issue by sidja** [angvp/django-changuito#19]
Traceback (most recent call last):
		  File "manage.py", line 10, in <module>
		    execute_from_command_line(sys.argv)
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
		    utility.execute()
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
		    django.setup()
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
		    apps.populate(settings.INSTALLED_APPS)
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
		    app_config = AppConfig.create(entry)
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
		    module = import_module(entry)
		  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
		    __import__(name)
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/changuito/__init__.py", line 1, in <module>
		    from proxy import CartProxy, ItemAlreadyExists, ItemDoesNotExist
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/changuito/proxy.py", line 3, in <module>
		    import models
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/changuito/models.py", line 7, in <module>
		    User = get_user_model()
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 150, in get_user_model
		    return django_apps.get_model(settings.AUTH_USER_MODEL)
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
		    self.check_models_ready()
		  File "/home/sid/.virtualenvs/temp/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
		    raise AppRegistryNotReady("Models aren't loaded yet.")
		django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

I've installed the app but unable go beyond this point. Any ideas on what could be going wrong here ?

**Comment by sidja** [comment]
Issue resolved 
https://github.com/angvp/django-changuito/commit/4e3f0bb25db7a12bda1e8f60eddc1c58f9b0a7a5
